#!/bin/sh

GTK_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini"
if [ ! -f "$GTK_CONFIG" ]; then exit 1; fi

get_value() {
	cut -d'=' -f2 | xargs
}

gtk_theme="$(grep 'gtk-theme-name' "$GTK_CONFIG" | get_value)"
icon_theme="$(grep 'gtk-icon-theme-name' "$GTK_CONFIG" | get_value)"
# cursor_theme="$(grep 'gtk-cursor-theme-name' "$GTK_CONFIG" | get_value)"
font_name="$(grep 'gtk-font-name' "$GTK_CONFIG" | get_value)"

gsettings set org.gnome.desktop.interface gtk-theme "$gtk_theme"
gsettings set org.gnome.desktop.interface icon-theme "$icon_theme"
# gsettings set org.gnome.desktop.interface cursor-theme "$cursor_theme"
gsettings set org.gnome.desktop.interface font-name "$font_name"
