[[plugins]]
repo = 'hrsh7th/nvim-cmp'
depends = ['LuaSnip', 'cmp_luasnip']
on_event = ['InsertEnter', 'CursorHold']
hook_source = '''
lua <<EOF
  local cmp = require 'cmp'
  local luasnip = require 'luasnip'
  local lspkind = require 'lspkind'

  require('luasnip.loaders.from_vscode').lazy_load()

  cmp.setup({
    snippet = {
      expand = function(args)
        luasnip.lsp_expand(args.body)
      end,
    },
    mapping = cmp.mapping.preset.insert({
      ['<C-d>'] = cmp.mapping.scroll_docs(-4),
      ['<C-f>'] = cmp.mapping.scroll_docs(4),
      ['<C-Space>'] = cmp.mapping.complete(),
      ['<C-e>'] = cmp.mapping.abort(),
      ['<CR>'] = cmp.mapping.confirm {
        behavior = cmp.ConfirmBehavior.Replace,
        select = false,
      },
      ['<Tab>'] = cmp.mapping(function(fallback)
        if cmp.visible() then
          cmp.select_next_item()
        elseif luasnip.expand_or_jumpable() then
          luasnip.expand_or_jump()
        else
          fallback()
        end
      end, { 'i', 's' }),
      ['<S-Tab>'] = cmp.mapping(function(fallback)
        if cmp.visible() then
          cmp.select_prev_item()
        elseif luasnip.jumpable(-1) then
          luasnip.jump(-1)
        else
          fallback()
        end
      end, { 'i', 's' })
    }),
    sources = cmp.config.sources({
      { name = 'npm', keyword_length = 4 },
      { name = 'nvim_lsp' },
      { name = 'nvim_lsp_signature_help' },
      { name = 'nvim_lua' },
      { name = 'luasnip' },
    }, {
      { name = 'buffer', keyword_length = 5 },
    }),
    formatting = {
      format = lspkind.cmp_format({
        mode = 'symbol', -- show only symbol annotations
        maxwidth = 50, -- prevent the popup from showing more than provided characters
      }),
    },
  })

  cmp.setup.filetype('gitcommit', {
    sources = cmp.config.sources({
      { name = 'cmp_git' },
    }, {
      { name = 'buffer' },
    }),
  })

  cmp.setup.cmdline('/', {
    mapping = cmp.mapping.preset.cmdline(),
    sources = cmp.config.sources({
      { name = 'nvim_lsp_document_symbol' }
    }, {
      { name = 'buffer' },
    }),
  })

  cmp.setup.cmdline(':', {
    mapping = cmp.mapping.preset.cmdline(),
    sources = cmp.config.sources({
      { name = 'path' },
    }, {
      { name = 'cmdline' },
    }),
  })
EOF
'''

[[plugins]]
repo = 'L3MON4D3/LuaSnip'
hook_add = '''
  inoremap <C-l> <Cmd>lua require('luasnip').expand_or_jump()<CR>
'''
[[plugins]]
repo = 'saadparwaiz1/cmp_luasnip'

[[plugins]]
repo = 'rafamadriz/friendly-snippets'
on_source = 'LuaSnip'

[[plugins]]
repo = 'onsails/lspkind.nvim'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp-document-symbol'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp-signature-help'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'petertriho/cmp-git'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lua'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'David-Kunz/cmp-npm'
on_source = 'nvim-cmp'
hook_source = '''
lua <<EOF
  require('cmp-npm').setup({})
EOF
'''

[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['nvim-cmp', 'cmp-nvim-lsp', 'nvim-lsp-installer']
on_source = 'nvim-cmp'
# on_ft = [
#   'bash', 'css', 'javascript', 'javascriptreact', 'sh', 'typescript', 'typescriptreact',
#   'go', 'python', 'vim'
# ]
if = 'has("nvim")'
# TODO: Install language servers automatically
#build = '''
#  !npm i -g typescript typescript-language-server vscode-langservers-extracted vim-language-server
#'''
hook_source = '''
lua <<EOF
  require('nvim-lsp-installer').setup { automatic_installation = true }

  local lspconfig = require('lspconfig')
  local on_attach = function(_, bufnr)
    local opts = { buffer = bufnr }
    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
    vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
    vim.keymap.set('n', 'gI', vim.lsp.buf.implementation, opts)
    vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
    vim.keymap.set('n', '<leader>wa', vim.lsp.buf.add_workspace_folder, opts)
    vim.keymap.set('n', '<leader>wr', vim.lsp.buf.remove_workspace_folder, opts)
    vim.keymap.set('n', '<leader>wl', function()
      vim.inspect(vim.lsp.buf.list_workspace_folders())
    end, opts)
    vim.keymap.set('n', '<leader>D', vim.lsp.buf.type_definition, opts)
    vim.keymap.set('n', '<leader>rn', vim.lsp.buf.rename, opts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
    vim.keymap.set('n', '<leader>ca', vim.lsp.buf.code_action, opts)
    vim.keymap.set('n', '<leader>so', require('telescope.builtin').lsp_document_symbols, opts)
    vim.api.nvim_create_user_command('Format', vim.lsp.buf.formatting, {})
  end

  local capabilities = vim.lsp.protocol.make_client_capabilities()
  capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)

  local servers = {
    'bashls',
    'cssls',
    'cssmodules_ls',
    'emmet_ls',
    'eslint',
    'graphql',
    'html',
    'jsonls',
    'pyright',
    'stylelint_lsp',
    'tailwindcss',
    'rust_analyzer',
    'tsserver',
    'vimls',
    'yamlls',
  }
  for _, lsp in ipairs(servers) do
    lspconfig[lsp].setup {
      on_attach = on_attach,
      capabilities = capabilities,
    }
  end

  local runtime_path = vim.split(package.path, ';')
  table.insert(runtime_path, 'lua/?.lua')
  table.insert(runtime_path, 'lua/?/init.lua')
  lspconfig.sumneko_lua.setup {
    on_attach = on_attach,
    capabilities = capabilities,
    settings = {
      Lua = {
        runtime = {
          version = 'LuaJIT',
          path = runtime_path,
        },
        diagnostics = {
          globals = { 'vim' },
        },
        workspace = {
          library = vim.api.nvim_get_runtime_file('', true),
        },
        telemetry = {
          enable = false,
        },
      },
    },
  }
EOF
'''

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
# on_lua = 'nvim-lsp-installer'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = 'plenary.nvim'
on_source = 'nvim-cmp'
hook_source = '''
lua <<EOF
  require('telescope').setup {
    defaults = {
      mappings = {
        i = {
          ['<C-u>'] = false,
          ['<C-d>'] = false,
        },
      },
    },
  }

  vim.keymap.set('n', '<leader><space>', require('telescope.builtin').buffers)
  vim.keymap.set('n', '<leader>sf', function()
    require('telescope.builtin').find_files()
  end)
  vim.keymap.set('n', '<leader>sv', function()
    require('telescope.builtin').find_files { cwd = vim.fn.stdpath('config') }
  end)
  vim.keymap.set('n', '<leader>sb', require('telescope.builtin').current_buffer_fuzzy_find)
  vim.keymap.set('n', '<leader>sh', require('telescope.builtin').help_tags)
  vim.keymap.set('n', '<leader>st', require('telescope.builtin').tags)
  vim.keymap.set('n', '<leader>sT', require('telescope.builtin').colorscheme)
  vim.keymap.set('n', '<leader>sd', require('telescope.builtin').grep_string)
  vim.keymap.set('n', '<leader>sp', require('telescope.builtin').live_grep)
  vim.keymap.set('n', '<leader>?', require('telescope.builtin').oldfiles)
EOF
'''

[[plugins]]
repo = 'nvim-telescope/telescope-fzf-native.nvim'
build = 'make'
depends = 'telescope.nvim'
on_source = 'telescope.nvim'
hook_source = '''
lua <<EOF
  require('telescope').load_extension 'fzf'
EOF
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
