[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'Shirk/vim-gas'

[[plugins]]
repo = 'chrisbra/vim-zsh'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
hook_source = '''
  let g:AutoPairsFlyMode = 0
  let g:AutoPairsShortcutToggle = ''
'''

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = """https://raw.githubusercontent.com/Shougo\
          /shougo-s-github/master/vim/colors/candy.vim"""
script_type = 'colors'
if = 'v:false'

[[plugins]]
repo = 'liuchengxu/space-vim-dark'
if = 'v:false'

[[plugins]]
repo = 'liuchengxu/space-vim-theme'
hook_source = '''
  "hi Comment guifg=#5C6370 ctermfg=59
  augroup MyAutoCmd
    autocmd VimEnter,ColorScheme *
    \ if !has('gui_running') | hi Normal ctermbg=NONE guibg=NONE | endif
  augroup END
'''
