abbr d docker
abbr db 'docker image build'
abbr dbt 'docker image build -t'
abbr dcn 'docker container'
abbr dcpr 'docker container prune'
abbr dhi 'docker image history'
abbr di 'docker image'
abbr dipr 'docker image prune'
abbr dlo 'docker container logs'
abbr dls 'docker image ls'
abbr dpl 'docker image pull'
abbr dps 'docker container ps'
abbr dpsa 'docker container ps --all'
abbr dpu 'docker image push'
abbr dr 'docker container run'
abbr drm 'docker container rm'
abbr drmi 'docker image rm'
abbr ds 'docker container start'
abbr dst 'docker container stop'
abbr dt 'docker image tag'

abbr dn 'docker network'

abbr dc 'docker compose'
abbr dcb 'docker compose build'
abbr dcd 'docker compose down'
abbr dcls 'docker compose ls'
abbr dcr 'docker compose run'
abbr dcu 'docker compose up'
abbr dcud 'docker compose up --detach'
abbr dcw 'docker compose up --watch'
abbr dcx 'docker compose exec'
