#!/bin/sh

config="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini"
if [ ! -f "$config" ]; then exit 1; fi

get_value() {
	cut -d'=' -f2 | xargs
}

gnome_schema="org.gnome.desktop.interface"
gtk_theme="$(grep 'gtk-theme-name' "$config" | get_value)"
icon_theme="$(grep 'gtk-theme-name' "$config" | get_value)"
cursor_theme="$(grep 'gtk-theme-name' "$config" | get_value)"
font_name="$(grep 'gtk-font-name' "$config" | get_value)"
gsettings set "$gnome_schema" gtk-theme "$gtk_theme"
gsettings set "$gnome_schema" icon-theme "$icon_theme"
gsettings set "$gnome_schema" cursor-theme "$cursor_theme"
gsettings set "$gnome_schema" font-name "$font_name"
gsettings set "$gnome_schema" text-scaling-factor 1
