#!/bin/bash

ID=2593
STEP_SIZE=5

usage() {
	echo "Usage: $(basename "$0") {up|down|mute}"
	exit 1
}

ui() {
	volume=$(pamixer --get-volume)
	declare -A verb=(
		[up]="Increasing"
		[down]="Decreasing"
	)
	declare -A icon=(
		[up]="audio-volume-high-symbolic"
		[down]="audio-volume-low-symbolic"
	)
	dunstify -a "VOLUME" "${verb[$1]} to $volume%" -h int:value:"$volume" \
		-i "${icon[$1]}" -r "$ID" -u normal
	canberra-gtk-play -i audio-volume-change -d changevolume
}

adjust() {
	if [ "$1" == "up" ]; then
		pamixer -i "$STEP_SIZE"
	elif [ "$1" == "down" ]; then
		pamixer -d "$STEP_SIZE"
	fi
}

mute() {
	pamixer -t
	muted="$(pamixer --get-mute)"
	if [ "$muted" = true ]; then
		dunstify "MUTED" -a "VOLUME" -i audio-volume-muted-symbolic -r "$ID" -u normal
	else
		dunstify "UNMUTED" -a "VOLUME" -i audio-volume-high-symbolic -r "$ID" -u normal
	fi
}

cmd="$1"
shift

case "$cmd" in
up | down)
	adjust "$cmd" && ui "$cmd"
	;;
mute) mute ;;
*)
	usage
	;;
esac
