PRX-8bLHVe7P8raRkpC7kUiH9os9vU4s-0:
  cellSpurs urgent commands hack - 4.90:
    "Metal Gear Solid 4: Guns of the Patriots":
      NPUB31633:
        All:
          Enabled: true
PPU-bbf4c85f1c01e182e7f96d34f734772c4430a426:
  Crash fix:
    "Metal Gear Solid 4: Guns of the Patriots":
      NPUB31633:
        02.00:
          Enabled: true