local map = vim.keymap.set

map('n', '<leader><space>', function()
  require('telescope.builtin').buffers()
end)
map('n', '<leader>sf', function()
  require('telescope.builtin').find_files()
end)
map('n', '<leader>sv', function()
  require('telescope.builtin').find_files { cwd = vim.fn.stdpath('config') }
end)
map('n', '<leader>sb', function()
  require('telescope.builtin').current_buffer_fuzzy_find()
end)
map('n', '<leader>sh', function()
  require('telescope.builtin').help_tags()
end)
map('n', '<leader>st', function()
  require('telescope.builtin').tags()
end)
map('n', '<leader>sT', function()
  require('telescope.builtin').colorscheme()
end)
map('n', '<leader>sd', function()
  require('telescope.builtin').grep_string()
end)
map('n', '<leader>sp', function()
  require('telescope.builtin').live_grep()
end)
map('n', '<leader>?', function()
  require('telescope.builtin').oldfiles()
end)
