live_config_reload = true
import = ["~/.config/alacritty/theme.toml"]

[env]

[window]
opacity = 0.9

[font]
size = 12.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[font.normal]
# family = "Maple Mono SC NF"
family = "JetBrainsMono Nerd Font"

[font.italic]
style = "Italic"
family = "Maple Mono SC NF"
# family = "VictorMono Nerd Font"

[font.bold_italic]
style = "Bold Italic"
family = "Maple Mono SC NF"
# family = "VictorMono Nerd Font"

[cursor]
style.blinking = "On"
style.shape = "Block"
vi_mode_style.shape = "Underline"
blink_interval = 500
blink_timeout = 10

[mouse]
hide_when_typing = true

[[hints.enabled]]
regex = '''(?:https?://|git@|git://|ssh://|ftp://|file:///)\S+'''
hyperlinks = true
post_processing = true
mouse = { enabled = true }
command = "xdg-open"

# [[hints.enabled]]
# # Too slow
# regex = '''\[[^]]*\]\(([^)]+)\)|(?:https?://|git@|git://|ssh://|ftp://|file:///)\S+|--- a/(\S+)|\+\+\+ b/(\S+)|sha256:([0-9a-f]{64})|(?:[.\w\-@~]+)?(?:/[.\w\-@]+)+|#[0-9a-fA-F]{6}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|[0-9a-f]{7,40}|\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}|[A-f0-9:]+:+[A-f0-9:]+[%\w\d]+|0x[0-9a-fA-F]+|[0-9]{4,}'''
# action = "Copy"
# binding = { key = "Space", mods = "Control | Shift", mode = "~Search" }

[[mouse.bindings]]
mouse = "Middle"
action = "None"

# FIXME: Keybinds don't work
[[keyboard.bindings]]
key = "L"
mods = "Control | Shift"
chars = '\x1b[76;5u'
[[keyboard.bindings]]
key = "H"
mods = "Control | Shift"
chars = '\x1b[72;5u'

[debug]
persistent_logging = false
